name: Build and Test

on: 
    workflow_call:
      inputs:
        upload-pages-artifact:
          type: boolean
          required: false
    workflow_dispatch: 

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with: 
                node-version: 22
            - run: npm i
            - run: npm run build
              env:
                BASE_PATH: '/${{ github.event.repository.name}}'
            - run: npx playwright install --with-deps
            - run: npm run test:e2e
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30
            - if: ${{ inputs.upload-pages-artifact }}
              uses: actions/upload-pages-artifact@v3.0.1
              with:
                path: build/
